export default function telegramReplacer(text) {
  return text
    .replace(/_/g,"\\_")
    .replace(/\*/g,"\\*")
    .replace(/\[/g,"\\[")
    .replace(/\(/g,"\\(")
    .replace(/\)/g,"\\)")
    .replace(/~/g,"\\~")
    .replace(/`/g,"\\`")
    .replace(/>/g,"\\>")
    .replace(/#/g,"\\#")
    .replace(/\+/g,"\\+")
    .replace(/-/g,"\\-")
    .replace(/=/g,"\\=")
    .replace(/\|/g,"\\|")
    .replace(/\{/g,"\\{")
    .replace(/\}/g,"\\}")
    .replace(/\./g,"\\.")
    .replace(/!/g,"\\!")
}